### PR TITLE
using libsuperuser to do SU tasks

### PR DESCRIPTION
**Pull request by SDkie**

### CODE REVIEW

**Comment by SDkie** [comment]
I have build both libsuperuser and lildebi using eclipse and tested it on Nexus 5 cm-11

**Comment by nroach44** [comment]
Thanks, looks good but the build fails with
```Buildfile: /home/nroach44/media/code/android-apps/lildebi/sdkie-lildebi-git/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.0.2
 [checkenv] Installed at /home/nroach44/apps/native/android-sdk-linux

-setup:
     [echo] Project Name: LilDebi
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:
     [echo] timestamp: 201502071936.27
    [apply] Applied touch to 17 files and 0 directories.

-build-setup:
[getbuildtools] Using latest Build Tools: 19.1.0
     [echo] Resolving Build Target for LilDebi...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
     [echo] ----------
     [echo] Resolving Dependencies for LilDebi...
[dependency] Library dependencies:
[dependency] 
[dependency] ------------------
[dependency] Ordered libraries:
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...

BUILD FAILED
/home/nroach44/apps/native/android-sdk-linux/tools/ant/build.xml:601: Invalid file: /home/nroach44/media/code/android-apps/lildebi/sdkie-lildebi-git/external/libsuperuser/libsuperuser/build.xml
```

**Comment by SDkie** [comment]
@nroach44 : I don't know how to make it work with command line. 
I just used eclipse to build both the projects.

**Comment by godlessfather** [comment]
There is no build.xml file for libsuperuser. It has a build.gradle file. This could be causing the failure.

**Comment by godlessfather** [comment]
Great patch, @SDkie. Tested working on CM12 with SuperSU and SlimKat with built-in superuser.

**Comment by eighthave** [comment]
@swisstengu you might be interested in this :-)

**Pull request merged**
